name: Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          playwright install chromium

      - name: Run Unit Tests
        run: |
          pytest tests/ -m "not network" --timeout=30 -v

  scraper-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    strategy:
      matrix:
        python-version: ['3.11']  # Only test scrapers on one Python version

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          playwright install chromium

      - name: Test Real Scrapers (Minimal Data)
        run: |
          pytest tests/test_scrapers_minimal.py -v --timeout=180
        continue-on-error: true  # Don't fail the entire CI if some scrapers are temporarily down
